# -*- coding: utf-8 -*-
"""aula_07_tratamento_erros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FFJspH_qgMVN8r25rIEIdK0ML2aTVyaX

# Entendendo mensagem de erros
"""

cat_attributes = {
    "name": "Zia",
    "age": 1,
    "color": "grey",
    }
breed = cat_attributes["breed"]


def add_pet(pets, name, age, species):
    pet = {"name": name, "age": age, "species": species, "fed": False}
    pets.append(pet)
add_pet(my_pets, "Zia", 2, "cat")

"""File "shelter.py" tells us which file has the error.
line 5 is the line where the error occurred.
NameError is the type of error.
name 'my_pets' is not defined tells us where we have the actual problem.
"""


